### ISSUE TITLE
use windguru API

### ISSUE THREAD

**Issue by Kikobeats** [JohnONolan/windwatch#1]
At this moment the localization to check wind status is locked. Would be amazing setup from the App settings.

I normally use [windguru](http://windguru.cz) for check the wind, and I saw that have an [API](http://stations.windguru.cz/json_api_stations.html). 

C'mon?!

**Comment by JohnONolan** [comment]
The point of windwatch is as a live weather reading, windguru is a forecast service.

I built this app for my own use at my local station, so I have no intention of expanding it. If you want to see any form of settings or support for other weather stations: Submit a PR.
